<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>J3L1XD</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <OutputPath>bin\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="dump.cs" />
    <Compile Remove="dumpinggame/**" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="BepInEx.Core">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/BepInEx.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="BepInEx.Unity.IL2CPP">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/BepInEx.Unity.IL2CPP.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/Il2CppInterop.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/Il2CppInterop.Common.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.UI">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.UI.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.AnimationModule">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.AnimationModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/Il2Cppmscorlib.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Unity.VisualScripting.Core">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/Unity.VisualScripting.Core.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="ACTk.Runtime">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/ACTk.Runtime.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="MoreMountains.Tools">
      <HintPath>$(BEPINEX_PATH)/BepInEx/interop/MoreMountains.Tools.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Il2CppInterop.HarmonySupport">
      <HintPath>$(BEPINEX_PATH)/BepInEx/core/Il2CppInterop.HarmonySupport.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
