name: windows-build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build Glass Overlay
        shell: cmd
        run: >
          msbuild examples\example_win32_directx11\example_win32_directx11.vcxproj
          /p:Configuration=Release
          /p:Platform=x64
          /p:PlatformToolset=v143
          /p:WindowsTargetPlatformVersion=10.0
          /v:minimal
          /nologo
